name: Publish latest embedded-toolchain images
on:
  push:
    branches:
      - main
    paths:
      - "images/embedded-toolchain/**"
      - ".github/workflows/publish-latest-embedded-toolchains.yaml"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "amd64,arm64"

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          builder: ${{ steps.setup_buildx.outputs.name }}
          workdir: "./images/embedded-toolchain"
          source: .
          files: "docker-bake.hcl,../globals.hcl"